spring:
  application:
    name: spring-cloud-service

server:
  port: 8763

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

